### ISSUE TITLE
restored cube daily loses board shape

### ISSUE THREAD

**Issue by gordonwoodhull** [gereleth/hexapipes#100]
I got stuck on today's daily and left the page. 

When I went back it looked like this:

![Screenshot_20230723_113524_Firefox](https://github.com/gereleth/hexapipes/assets/1366709/46a963a6-ecba-4b6f-a132-56ae8a6831ca)

**Comment by gereleth** [comment]
Weird, it restores without issues on my end. Have you tried refreshing the page? Maybe you're running a stale version of the code...

**Comment by gordonwoodhull** [comment]
Yep, fixed on refresh. Probably a browser caching issue.
