### ISSUE TITLE
Ambiguity in Hexagonal wrap 10x10 756

### ISSUE THREAD

**Issue by Lanzaa** [gereleth/hexapipes#24]
In the 10x10 hexagonal wrap [puzzle 756](https://hexapipes.vercel.app/hexagonal-wrap/10/756) there is an ambiguous section.

Here is the nearly finished puzzle with the ambiguous area unfinished: [nearly done 756](https://user-images.githubusercontent.com/240881/181679399-d101aa03-f7f2-4ecd-94d5-c4a5e37ea210.png).

**Comment by gereleth** [comment]
Oops, looks like you're right. Thanks for reporting!

I'll check how the generator sneaked this in :/.

**Comment by gereleth** [comment]
Seems like there's a bug in my solver that causes it to miss this kind of ambiguities. Here's an example of a 3x3 non-wrap puzzle with the same pattern. The solver reports a single solution in this case too but it's clear that the right side could go two ways =(. 

![image](https://user-images.githubusercontent.com/6080076/181705217-5003958e-de10-4fe2-9303-44f029eabf12.png)

I'll need to dig in to see why this happens.

**Comment by gereleth** [comment]
I have found the bug. It looks like 528 puzzles out of 12000 total were affected. Most of the affected puzzles have two solutions with an occasional 3 or 4. Here's an example of a fun spot that produces three different solutions:

![an example of tiles configuration producing three different solutions](https://user-images.githubusercontent.com/6080076/181811394-3654db68-b6c7-40bd-ba36-6d14b1b56734.png)

I'm going to replace some tiles in the affected puzzles to enforce a unique solution. 

Thanks so much for bringing this to my attention! I played a whole lot of the puzzles and never noticed =).

**Comment by gereleth** [comment]
Ok, on a more accurate count this concerned about ~260 wrap puzzles. All the non-wrap ones were fine.

I have replaced some tiles in the affected puzzles to remove the ambiguity. Number 756 now looks like 
[this](https://user-images.githubusercontent.com/6080076/181913984-4a0bc2cd-fa6e-44d3-9ef7-fbe723e3efd0.png) (with the same four tiles left unlocked).

Hopefully there are no more puzzles with multiple solutions but if you notice any please open a new issue.
