### ISSUE TITLE
Add larger wraps than just 15x15

### ISSUE THREAD

**Issue by rixx** [gereleth/hexapipes#25]
It would be neat to be able to play wraps up to the same size as non-wraps!

**Comment by gereleth** [comment]
Done, have a go at them. Let me know how long a 40x40 takes :).

**Comment by rixx** [comment]
Disclaimer: on a train full of distractions, had to change trains once, and also used a shitty touchpad. Thank you for the time ~~well~~ spent!
![Uploading 2022-08-01T19:19:26+02:00.png…]()

**Comment by rixx** [comment]
Disclaimer: on a train full of distractions, had to change trains once, and also used a shitty touchpad. Thank you for the time ~~well~~ spent!
![2022-08-01T19:19:26+02:00](https://user-images.githubusercontent.com/2657547/182208366-dea3a9cf-6954-461e-a519-cdc4e346c318.png)
