### ISSUE TITLE
Mobile device improvements ?

### ISSUE THREAD

**Issue by ginabythebay** [gereleth/hexapipes#30]
Hi thanks so much for this awesome game!
I’m playing on phone/tablet and it is impossible for me to use the gestures to lock tiles or to mark the walls (occasionally I will accidentally mark the walls but I can never seem to do it on purpose).

Perhaps there is some kind of gesture or double tap or mode or something to help with that?  Also, I think it would be nice to just be able to reset the board to the starting point somehow.

**Comment by gereleth** [comment]
Could you share your device and browser info?

Locking tiles is done by longpress for me. What happens when you do this?

Maybe this is a zoom issue? I use pinch to zoom on my phone to make tiles and edges larger and easier to touch accurately.

As for start over button there's an issue for it #17 . I'll do it soon enough probably.

**Comment by ginabythebay** [comment]
I’m having the problem on safari on both an iPhone 13 pro xl and on an early iPad Pro.

Pinch to zoom makes it possible for me to touch edges accurately, if I am willing to tolerate a ~50% error rate where instead I accidentally rotate a tile.  Unfortunately this means i must then go fix the misrotated tile, and the hole thing starts to seem more like work than a game.

I have never had long press work successfully on these devices.

**Comment by gereleth** [comment]
Yeah, this doesn't sound fun at all.

I had some ideas about gesture based controls for touch devices. For example, touch and move back and forth along the edge a couple of times to make a wall mark. The same across the edge to make a connection mark. Maybe even a touch and draw an arc for rotating tiles (like a rotary phone).

My main concern is that touch and drag is the normal way to move around the page - especially when zoomed in. And gestures would have to interfere with this which could be the same kind of frustrating.

If you have any ideas about creating a comfortable touch experience for this game then please share them here. I may implement something once I have a better idea of requirements.
