### ISSUE TITLE
Check mistake button

### ISSUE THREAD

**Issue by ledowong** [gereleth/hexapipes#32]
Thanks.
In some senses, this game similar to Picross. In Switch Picross (https://www.google.com/search?q=switch+picross), there is a check mistake feature which really useful, especially playing large puzzle, at the very end of the game you found it doesn't connect, but don't want to start all over again.

**Comment by gereleth** [comment]
Well the tile that didn't connect is itself a hint for where you should look for mistakes =). 

If I have a disconnect I can't easily fix then I check my logic by starting at a nearby edge and locking tiles that have only one possible orientation and/or marking known edges. The locked tiles will usually propagate and give some insight to where things went wrong.

Or do you mean a situation where the locked tiles themselves have some inconsistency between them?

As currently implemented the game doesn't know the correct solution to a puzzle. It just notices when you connect everything =). So I can't easily add an error check unless I port the solver code (my solver/generator are in python). If I do ever port them then we could have error checking or even a guided solving tutorial with hints. But I think this is a low priority for now.

**Comment by ledowong** [comment]
understand that, thanks.

**Comment by ledowong** [comment]
Do you mean each puzzle has more than one solution?

**Comment by gereleth** [comment]
No, there is a single solution. I mean the checking code doesn't know correct orientations of tiles. It isn't comparing your solution with the correct answer like "if the first tile has 2 rotations, and the second tile has 4 rotations and so on then the puzzle is solved". It just checks if all pipes are connected into a single network.

**Comment by ledowong** [comment]
If thats the case, maybe just use the generator (python) to export both puzzle and solution (the answer). No need to port the whole script to JS.
JS just check if any freezed (right click) hex does not match with the answer and highlight it.
