### ISSUE TITLE
Improved scrolling (plus panning?)

### ISSUE THREAD

**Issue by eminence** [gereleth/hexapipes#33]
Hello!  First:  this is a wonderful game!

I'm writing to share some UX feedback on the wrap variant.

This mode really benefits from the edge marks to rule out certain edges.  However, since the click target for the edge markers is so tiny, I like to zoom in quite a bit to make clicking easier.  My first comment is that zooming is rather slow.  For example, to zoom in from an overview (where there's only 1 or 2 tiles repeated on the edges) to a zoom that's comfortable to click edges takes about 5 seconds.  This is something like ~10 full rotations of the scroll wheel on my mouse.

The second comment is related to the first -- since zooming is rather slow, I find myself wishing there was a way to pan around the zoomed-in tiles.

**Comment by gereleth** [comment]
Hi, glad you're enjoying it.

Thanks for the feedback. I'm aware of the zoom issues and the lack of panning =). My other project has an overeager wheel zoom and I may have overcorrected quite a bit here)).

I have some tentative ideas for how to improve this part. I can ping you when there's a preview link to try out the changes.

**Comment by gereleth** [comment]
So I made panning kinda work with a mouse click and drag action. But the click handlers on tiles and edgemarks still fire when I let go. And the clicks sometimes pan a tiny amount. I dread sorting out the event handlers)).

Nothing done for touch devices for now.

You can check how it works in the linked pull request, look for a "Visit Preview" link in a message from Vercel.
