### ISSUE TITLE
Pause button

### ISSUE THREAD

**Issue by ledowong** [gereleth/hexapipes#35]
Freeze the game and stop the timer. =)

**Comment by gereleth** [comment]
Oh no, please just ignore the timer or hide it if you don't like what it's showing 😄.

I'd rather not build more complexity around it.

**Comment by joshwilsonvu** [comment]
I understand your concern about adding a manual pause button, but I'm curious if you might be interested in a PR for automatically pausing the timer when the tab is hidden/closed by using (the visibility change event)[https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event].

I think all it would take is one new field on a stored `solve` object, a `pausedAt` time, which is set when the document becomes hidden. Then, when the document becomes visible, we subtract `pausedAt` from the current time, and move `startedAt` forward by that exact amount, so the resulting `elapsed` is adjusted to pick up exactly where it left off.

For larger puzzles especially, I think being able to give more accurate times when players can't complete the puzzle in a single sitting is a nice usability bonus. Love the game by the way!

**Comment by gereleth** [comment]
Well this sounds slightly more appealing, I'll reopen I guess)).

To keep with the spirit the pause would also have to start when navigating away from the puzzle, not only on switching tabs.
