### ISSUE TITLE
Edge marks not working

### ISSUE THREAD

**Issue by rjsmith64** [gereleth/hexapipes#39]
Edit: Working as designed (edge marks drawn by gesture) - would be nice for this to be configurable. Clicking the edges was easier for me on non-mobile.

Edge marks seem not to be working in Chrome 104.0.5112.81 (and were working previously). Mousing over the edge between cells does not cause the cursor to change. Clicking the edge between cells causes cell rotation.

**Comment by gereleth** [comment]
You can also click near the edge middle and hold a little to make a mark (left button = wall, right = connection). 

I was getting a lot of unintentional marks from clicking around before and I wanted to reduce probability of that.

**Comment by rjsmith64** [comment]
Yes I just discovered that too. The gesture controls are growing on me :). Thanks!
