### ISSUE TITLE
Timer does not reset on start over

### ISSUE THREAD

**Issue by gordonwoodhull** [gereleth/hexapipes#48]
I think the “start over” button used to reset the timer. IMO it should!

Love this game, totally addicted. The recent interface improvements are awesome!

**Comment by gereleth** [comment]
It never did! And I don't think it should)).

IMO the timer measures how long it takes you to go from seeing the puzzle for the first time to having a solution. Starting over is just one of the tools you can use in the process. 

If the timer resets on start over then it kinda motivates you to do a "test run" first to figure out the solution, then start over and do a "perfect run" knowing the solution already. I don't want to encourage this). 

> Love this game, totally addicted. The recent interface improvements are awesome!

Thanks for your kind words, this gives me a nice motivation boost =).

**Comment by gordonwoodhull** [comment]
Fair enough, no interest in speedruns, just wanted to avoid those absurd “16 day” times I got from exploring the options or giving up and doing something else. 

That shouldn’t happen as much with the new pausing timer, or I’ll just skip to the next puzzle!
