### ISSUE TITLE
15x15 requires scrolling in the display window

### ISSUE THREAD

**Issue by paulehoffman** [gereleth/hexapipes#59]
In both Chrome and Firefox on a laptop with a good-sized screen, the 15x15 puzzle does not appear fully within the viewframe; scrolling by dragging is required. It would be great if there was a way to indicate that we would like a reduced-size puzzle so we don't have to drag while solving.

**Comment by gereleth** [comment]
Two options here:

1) You can zoom out. There's a catch here that the puzzle won't take full height of the screen. Some vertical space is left to permit scrolling the page.

2) You can disable zoom/pan in settings and then the puzzle will fit your screen using its full height.

I'm thinking of changing layout to get rid of the need for scrolling the page (#44 ). But to be honest I don't expect that to be done any time soon)).

**Comment by paulehoffman** [comment]
1. Zooming out on Chrome and Firefox (at least on the Mac) do not affect the problem: the whole screen shrinks, including the viewport.

2. Ohmygosh I never saw the "Settings" link! Thanks, that exactly solves the problem.
