### ISSUE TITLE
Make the Settings more obvious

### ISSUE THREAD

**Issue by paulehoffman** [gereleth/hexapipes#60]
The settings (which turned out very valuable to me!) are a small text line that are easily lost. Making them bigger (a button?) and centered somewhere might make folks notice them more.

**Comment by gereleth** [comment]
I'm thinking of moving the settings down to puzzle buttons to replace the "Hide timer" button.

![screenshot](https://user-images.githubusercontent.com/6080076/206925354-00086e15-68e4-4461-b6d2-93f0d3eb8db0.png)

[Preview link](https://hexapipes-git-settings-gereleth.vercel.app/hexagonal/5) to to try it out.
