### ISSUE TITLE
Layout keeps repeating itself (see image)

### ISSUE THREAD

**Issue by kpingka** [gereleth/hexapipes#61]
Did something break in the tile generation?
![image](https://user-images.githubusercontent.com/68285618/191222001-3ea6f979-3233-4dcd-ac16-d889bf1a6f17.png)

**Comment by Aaron-Rumpler** [comment]
It's a wrap puzzle, so it's supposed to do that.

From the website:

> Wrap pipes are a challenging variation of the puzzle. The connections in this variant are allowed to wrap between borders of the board. Imagine copies of the puzzle placed on all sides of it (left, right, top and bottom). This way tiles on the right border can connect to tiles on the left border - or "wrap" around.
>
> Unlike regular pipes puzzles the wrap variant has no convenient outer walls to start the deductions from. Hence its increased difficulty. To help deal with wrap edges multiple copies of the puzzle are shown, tiling the screen. When you rotate a tile all its copies will rotate too.

**Comment by kpingka** [comment]
Im a dummy :)
