### ISSUE TITLE
404 on daily

### ISSUE THREAD

**Issue by gordonwoodhull** [gereleth/hexapipes#66]
Went to check out the first puzzle of 2023 but I get a 404. Oh no!

![96F78DE9-75DF-489F-BAAD-AAA5AF5CCED5](https://user-images.githubusercontent.com/1366709/210157971-2e50e9cb-9fa2-4a6d-a581-e5236741675a.jpeg)

**Comment by gereleth** [comment]
Sigh...

I made a commit adding some new dailies... But the deploy failed. 

I guess I haven't been keeping up with Svelte Kit changes recently and something broke. 

Happy new year sob :'(

**Comment by gereleth** [comment]
I pinned `adapter-vercel` to some previous version and the deploy went through. The daily page should work now.

**Comment by gordonwoodhull** [comment]
Happy new year!

Yes framework churn is no fun.

Great puzzle though,  thanks!
