### ISSUE TITLE
Placement of red and green bars is broken

### ISSUE THREAD

**Issue by bartwensley** [gereleth/hexapipes#97]
Since the last update placement of the red and green bars is broken - for example, left-clicking and holding on the yellow X puts the red bar in the wrong location in the following screensnip:
<img width="265" alt="image" src="https://github.com/gereleth/hexapipes/assets/5198701/a5089681-50ad-4718-9b2b-3e717e924205">
It is pretty much random where the bars appear now - usually on the wrong edge of the current square/hex/whatever.
I'm seeing this on Chrome (Windows 10).

**Comment by gereleth** [comment]
Oops, sorry about this! Forgot to invert y sign in one last place. Well hopefully last =).

I should probably make a prerelease testing protocol... I usually just play in the preview site but this bug slipped in because I almost never use this feature. Thanks for reporting!
